version: 2.1
workflows: 
  test-deploy:
    jobs:
      - test
test:
  docker:
    - image: cimg/python:3.11.0
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: run test
        command : python -m pytest
     