version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: run test
          command : python -m pytest
workflows: 
  test-deploy:
    jobs:
      - build_and_test